# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170706_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userprofile',
            new_name='Profile',
        ),
    ]
